baseURL = 'https://ilisim.github.io/'
languageCode = 'en-us'
title = 'Mano naujas puslapis'
theme = "hello-friend"
cover.hidden = false # hide everywhere but not in structured data
cover.hiddenInList = false # hide on list pages and home
cover.hiddenInSingle = false # hide on single page


